Rename some functions to something easier understand
LCSB-BioCore/SBML.jl pull request #122
Opened 2021-07-16 15:32 UTC by giordano

* `getS` -> `stoichiometry_matrix`
* `getLBs`, `getUBs` -> `flux_bounds`
* `getOCs` -> `flux_objective`

Fix #121.

2021-07-17 17:02 UTC, exaexa requested changes
LGTM, except the [1] vs [2] index.

2021-07-17 17:02 UTC, exaexa commented on test/ecoli_flux.jl
> +    @test length(flux_bounds(mdl)[2]) == length(rxns)
there should be `[1]` here right?

2021-07-17 22:37 UTC, giordano commented on test/ecoli_flux.jl
> +    @test length(flux_bounds(mdl)[2]) == length(rxns)
Ugh, yes, thanks!  Fixed

2021-07-19 12:53 UTC, exaexa commented
oh noes I trusted the github "resolve conflicts" button :D

2021-07-19 12:54 UTC, exaexa approved these changes

2021-07-19 13:04 UTC, merged