Events support
LCSB-BioCore/SBML.jl pull request #165
Opened 2021-12-13 20:21 UTC by anandijain

I'll need to add the delays and the `useValuesFromTriggerTime` attribute later, but this is a good starting point for what i need done in the short term. Since it doesn't seem that the delays can be used easily in MTK yet, I can put that off for another PR.

2021-12-13 20:54 UTC, exaexa approved these changes
Looks good to me. We may wait for @giordano in case of any comments, but otherwise I think this is ready to merge.

2021-12-13 20:57 UTC, exaexa requested changes

2021-12-13 20:57 UTC, exaexa commented on src/structs.jl
> +    name
naaaah, this needs types.

2021-12-14 13:30 UTC, giordano reviewed
Looks good to me, apart from the missing type annotations

2021-12-14 13:30 UTC, giordano commented on src/readsbml.jl
> +        event_assignments = []
```suggestion
        event_assignments = EventAssignment[]
```

2021-12-14 20:30 UTC, exaexa approved these changes
cool thanks!

2021-12-14 22:22 UTC, merged